# coding: utf-8

"""
    Clever API

    The Clever API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.models.users_updated import UsersUpdated  # noqa: E501
from clever.rest import ApiException


class TestUsersUpdated(unittest.TestCase):
    """UsersUpdated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUsersUpdated(self):
        """Test UsersUpdated"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever.models.users_updated.UsersUpdated()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
