# coding: utf-8

"""
    Clever API

    The Clever API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.models.resource_object import ResourceObject  # noqa: E501
from clever.rest import ApiException


class TestResourceObject(unittest.TestCase):
    """ResourceObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceObject(self):
        """Test ResourceObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever.models.resource_object.ResourceObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
