# coding: utf-8

"""
    Clever API

    The Clever API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.api.data_api import DataApi  # noqa: E501
from clever.rest import ApiException


class TestDataApi(unittest.TestCase):
    """DataApi unit test stubs"""

    def setUp(self):
        self.api = DataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_contacts_for_user(self):
        """Test case for get_contacts_for_user

        """
        pass

    def test_get_course(self):
        """Test case for get_course

        """
        pass

    def test_get_course_for_section(self):
        """Test case for get_course_for_section

        """
        pass

    def test_get_courses(self):
        """Test case for get_courses

        """
        pass

    def test_get_courses_for_resource(self):
        """Test case for get_courses_for_resource

        """
        pass

    def test_get_courses_for_school(self):
        """Test case for get_courses_for_school

        """
        pass

    def test_get_district(self):
        """Test case for get_district

        """
        pass

    def test_get_district_for_course(self):
        """Test case for get_district_for_course

        """
        pass

    def test_get_district_for_school(self):
        """Test case for get_district_for_school

        """
        pass

    def test_get_district_for_section(self):
        """Test case for get_district_for_section

        """
        pass

    def test_get_district_for_term(self):
        """Test case for get_district_for_term

        """
        pass

    def test_get_district_for_user(self):
        """Test case for get_district_for_user

        """
        pass

    def test_get_districts(self):
        """Test case for get_districts

        """
        pass

    def test_get_resource(self):
        """Test case for get_resource

        """
        pass

    def test_get_resources(self):
        """Test case for get_resources

        """
        pass

    def test_get_resources_for_course(self):
        """Test case for get_resources_for_course

        """
        pass

    def test_get_resources_for_section(self):
        """Test case for get_resources_for_section

        """
        pass

    def test_get_resources_for_user(self):
        """Test case for get_resources_for_user

        """
        pass

    def test_get_school(self):
        """Test case for get_school

        """
        pass

    def test_get_school_for_section(self):
        """Test case for get_school_for_section

        """
        pass

    def test_get_schools(self):
        """Test case for get_schools

        """
        pass

    def test_get_schools_for_course(self):
        """Test case for get_schools_for_course

        """
        pass

    def test_get_schools_for_term(self):
        """Test case for get_schools_for_term

        """
        pass

    def test_get_schools_for_user(self):
        """Test case for get_schools_for_user

        """
        pass

    def test_get_section(self):
        """Test case for get_section

        """
        pass

    def test_get_sections(self):
        """Test case for get_sections

        """
        pass

    def test_get_sections_for_course(self):
        """Test case for get_sections_for_course

        """
        pass

    def test_get_sections_for_resource(self):
        """Test case for get_sections_for_resource

        """
        pass

    def test_get_sections_for_school(self):
        """Test case for get_sections_for_school

        """
        pass

    def test_get_sections_for_term(self):
        """Test case for get_sections_for_term

        """
        pass

    def test_get_sections_for_user(self):
        """Test case for get_sections_for_user

        """
        pass

    def test_get_students_for_user(self):
        """Test case for get_students_for_user

        """
        pass

    def test_get_teachers_for_user(self):
        """Test case for get_teachers_for_user

        """
        pass

    def test_get_term(self):
        """Test case for get_term

        """
        pass

    def test_get_term_for_section(self):
        """Test case for get_term_for_section

        """
        pass

    def test_get_terms(self):
        """Test case for get_terms

        """
        pass

    def test_get_terms_for_school(self):
        """Test case for get_terms_for_school

        """
        pass

    def test_get_user(self):
        """Test case for get_user

        """
        pass

    def test_get_users(self):
        """Test case for get_users

        """
        pass

    def test_get_users_for_resource(self):
        """Test case for get_users_for_resource

        """
        pass

    def test_get_users_for_school(self):
        """Test case for get_users_for_school

        """
        pass

    def test_get_users_for_section(self):
        """Test case for get_users_for_section

        """
        pass


if __name__ == '__main__':
    unittest.main()
