# coding: utf-8

"""
    Clever API

    The Clever API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.models.terms_created import TermsCreated  # noqa: E501
from clever.rest import ApiException


class TestTermsCreated(unittest.TestCase):
    """TermsCreated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTermsCreated(self):
        """Test TermsCreated"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever.models.terms_created.TermsCreated()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
