# coding: utf-8

"""
    Clever API

    The Clever API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.models.districts_updated import DistrictsUpdated  # noqa: E501
from clever.rest import ApiException


class TestDistrictsUpdated(unittest.TestCase):
    """DistrictsUpdated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDistrictsUpdated(self):
        """Test DistrictsUpdated"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever.models.districts_updated.DistrictsUpdated()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
